# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-21 08:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20171121_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='avatar',
            field=models.FileField(default='/avatar/default.png', upload_to='avatar/', verbose_name='头像'),
        ),
    ]
