# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-21 11:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20171121_1608'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='分类子标题')),
            ],
            options={
                'verbose_name_plural': '博客主页子菜单标题',
            },
        ),
        migrations.CreateModel(
            name='SiteMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='分类主标题')),
            ],
            options={
                'verbose_name_plural': '博客主页主菜单标题',
            },
        ),
        migrations.RemoveField(
            model_name='article',
            name='article_type_id',
        ),
        migrations.AddField(
            model_name='sitecategory',
            name='siteMenu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.SiteMenu', verbose_name='所属主标题'),
        ),
        migrations.AddField(
            model_name='article',
            name='siteCategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='article', to='app01.SiteCategory', verbose_name='所属博客系统分类'),
            preserve_default=False,
        ),
    ]
