# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-21 11:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_auto_20171121_1935'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article2tag',
            options={'verbose_name_plural': '文章标签表'},
        ),
        migrations.AlterModelOptions(
            name='articleup',
            options={'verbose_name_plural': '文章点赞表'},
        ),
        migrations.AlterModelOptions(
            name='commentup',
            options={'verbose_name_plural': '评论点赞表'},
        ),
    ]
