# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-22 11:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_auto_20171122_1435'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name_plural': '标签博客表'},
        ),
    ]
